#
server:
  port: 8762

environments:
  development:
    datasource:
      mysqlDatabase: db_bahay
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: rootmysql
      MYSQL_PORT: 3306
      ENTITY_TO_SCAN: com.ascii274.login.entity
      URL: jdbc:mysql://localhost

# Configuration webapp directory
spring:
  thymeleaf:
    template-resolver-order: 0
    prefix: classpath:./webapp/WEB-INF/view/


#spring.thymeleaf.prefix=classpath:./webapp/WEB-INF/templates/
#
#spring:
#  datasource:
##    driver-class-name: com.mysql.jdbc.Driver #original deprecated
#    driver-class-name: com.mysql.cj.jdbc.Driver #baeldung
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:8081/login
#    username: root
#    password: bahay1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#
#
#    properties:
#      hibernate:
#        dialect=org.hibernate.dialect.MySQL5Dialect



